# --- ???????? ????????? ---
spring.application.name=ewm-main-service
server.port=8080

# --- ??????? ??? (????? GitHub ? wait-for-it ??????? ????) ---
# ?????????? Java ???????????? IPv4, ??? ??? ??????? ????? ?? ????? ???? ?? IPv6
java.net.preferIPv4Stack=true
# ???????? ?????? ???????, ???????? ?????? ??????
server.tomcat.max-threads=1
spring.main.lazy-initialization=true

# --- ???? ?????? ---
# ?????????? ??? ??????? ?? docker-compose
spring.datasource.url=jdbc:postgresql://main-db:5432/ewm_main
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIKARI (????????? ????????) ---
# -1 ?????????? ??? ?????????? ???????? ????????????, ???? ???? ?? ?????????
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=30000

# --- HIBERNATE / JPA ---
# ???? ?????? ???????, ????? Spring ?? ??? ? ???? ?? ??????????? ??? ?????? (???????? 5-10 ???)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
# ????????? ???????? ?????, ??? ??? ?? ??????? ??? ????? ????????? ?????
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# --- ????????????? ---
# ???? ????? ???? ??????? ???????, ?????? 'never'. ???? ????? ??????? schema.sql ? 'always'
spring.sql.init.mode=always
spring.datasource.continue-on-error=true

# --- ?????? ???? ---
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC

# --- ?????????? ---
stats.server.url=http://stats-server:9090

# --- ???? (????????? ??? ????????) ---
# ????? ? ??????? ?? ?????? ???????? ?????? ????????? ?????????? ?????
logging.level.root=OFF
logging.level.org.springframework=OFF
logging.level.ru.practicum=OFF

# --- SWAGGER (?????????) ---
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false