spring.application.name=ewm-main-service
server.port=8080

spring.datasource.url=jdbc:postgresql://main-db:5432/ewm_main
spring.datasource.username=admin
spring.datasource.password=password
spring.sql.init.mode=always

spring.datasource.hikari.initialization-fail-timeout=1

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC
stats.server.url=http://stats-server:9090
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false