spring.application.name=ewm-main-service
server.port=8080

spring.datasource.url=jdbc:postgresql://main-db:5432/ewm_main
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.sql.init.mode=always
spring.datasource.continue-on-error=true

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC

stats.server.url=http://stats-server:9090

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
logging.level.root=WARN
logging.level.ru.practicum=INFO