CREATE TABLE IF NOT EXISTS users (
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  VARCHAR(250) NOT NULL,
  email VARCHAR(254) NOT NULL,
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations (
  id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lat FLOAT NOT NULL,
  lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  annotation         VARCHAR(2000) NOT NULL,
  category_id        BIGINT REFERENCES categories (id) ON DELETE CASCADE,
  confirmed_requests BIGINT,
  created_on         TIMESTAMP WITHOUT TIME ZONE,
  description        VARCHAR(7000) NOT NULL,
  event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  initiator_id       BIGINT REFERENCES users (id) ON DELETE CASCADE,
  location_id        BIGINT REFERENCES locations (id) ON DELETE CASCADE,
  paid               BOOLEAN NOT NULL,
  participant_limit  INT DEFAULT 0,
  published_on       TIMESTAMP WITHOUT TIME ZONE,
  request_moderation BOOLEAN DEFAULT TRUE,
  state              VARCHAR(20),
  title              VARCHAR(120) NOT NULL,
);

CREATE TABLE IF NOT EXISTS requests (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created      TIMESTAMP WITHOUT TIME ZONE,
  event_id     BIGINT REFERENCES events (id) ON DELETE CASCADE,
  requester_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
  status       VARCHAR(20),
  CONSTRAINT unique_user_request UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT REFERENCES compilations(id) ON DELETE CASCADE,
    event_id       BIGINT REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_events_state ON events (state);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events (event_date);
CREATE INDEX IF NOT EXISTS idx_user_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_category_name ON categories (name);